name: Build, test and publish
on:
  push:
    branches:
      - master

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      project-path: 
        /target:libs\Mvvm_CommonInteractions_Core
        /target:libs\Mvvm_CommonInteractions_Uno
        /target:libs\Mvvm_CommonInteractions_Uno_WinUI
        /target:libs\Mvvm_CommonInteractions_Uwp
        /target:libs\Mvvm_CommonInteractions_WinUI
        /target:libs\Mvvm_CommonInteractions_Wpf
        /target:libs\Mvvm_CommonInteractions_Maui
        /target:libs\Mvvm_CommonInteractions_Avalonia
      use-msbuild: true
      workloads: maui
      install-tizen: true
      windows-sdk-version: 18362
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}

#  WebAssembly:
#    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
#    with:
#      os: windows-latest
#      project-path: src/apps/Mvvm.Apps.Uno
#      deploy-web-assembly-path: src/apps/Mvvm.Apps.Uno/bin/Release/net8.0-webassembly/dist
#      generate-build-number: false
#      workloads: maui