name: Build and test
on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build abd test
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-latest
      project-path:
        /target:libs\Mvvm_Interactions_Core
        /target:libs\Mvvm_Interactions_Uno
        /target:libs\Mvvm_Interactions_Uno_WinUI
        /target:libs\Mvvm_Interactions_Uwp
        /target:libs\Mvvm_Interactions_WinUI
        /target:libs\Mvvm_Interactions_Wpf
        /target:libs\Mvvm_Interactions_Maui
        /target:libs\Mvvm_Interactions_Avalonia
      use-msbuild: true
      workloads: maui
      install-tizen: true
      windows-sdk-version: 18362
      generate-build-number: false
      conventional-commits-publish-conditions: false