name: Build and test
on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build abd test
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-2022
      project-path:
        /target:libs\Mvvm_CommonInteractions_Core
        /target:libs\Mvvm_CommonInteractions_Uno
        /target:libs\Mvvm_CommonInteractions_Uno_WinUI
        /target:libs\Mvvm_CommonInteractions_Uwp
        /target:libs\Mvvm_CommonInteractions_WinUI
        /target:libs\Mvvm_CommonInteractions_Wpf
        /target:libs\Mvvm_CommonInteractions_Maui
        /target:libs\Mvvm_CommonInteractions_Avalonia
      use-msbuild: true
      workloads: maui android ios maccatalyst macos
      install-tizen: true
      windows-sdk-version: 18362
      generate-build-number: false
      conventional-commits-publish-conditions: false